version: '3.1'
services:
    mysql:
        container_name: mysql
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        network_mode: host
        environment:
            MYSQL_ROOT_PASSWORD: 'pass'
        volumes:
            - hedgecast_mysql:/var/lib/mysql

volumes:
    hedgecast_mysql:
