"""empty message

Revision ID: 01b4df4ec901
Revises: a9a478db66d5
Create Date: 2019-02-27 03:01:16.058060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b4df4ec901'
down_revision = 'a9a478db66d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_playlist', sa.Column('order_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_playlist', 'order_by')
    # ### end Alembic commands ###
