"""empty message

Revision ID: 0a336024e80d
Revises: c21d14788831
Create Date: 2019-02-26 06:30:20.685826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a336024e80d'
down_revision = 'c21d14788831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('category', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
