"""empty message

Revision ID: 0da60609ddb1
Revises: 0a336024e80d
Create Date: 2019-02-27 01:10:06.570863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0da60609ddb1'
down_revision = '0a336024e80d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('playlist_ibfk_1', 'playlist', type_='foreignkey')
    op.drop_column('playlist', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('playlist_ibfk_1', 'playlist', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
