"""empty message

Revision ID: 139a40eafdc2
Revises: 01b4df4ec901
Create Date: 2019-02-27 04:54:35.933800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '139a40eafdc2'
down_revision = '01b4df4ec901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'enabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('video', 'enabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'enabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'enabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###
