"""empty message

Revision ID: 9913cbe44078
Revises: a08fae24c425
Create Date: 2019-03-25 17:41:27.170818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9913cbe44078'
down_revision = 'a08fae24c425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_playlist', sa.Column('order', sa.Integer(), nullable=True))
    op.drop_column('video_playlist', 'order_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_playlist', sa.Column('order_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('video_playlist', 'order')
    # ### end Alembic commands ###
