"""empty message

Revision ID: a9a478db66d5
Revises: 0da60609ddb1
Create Date: 2019-02-27 03:00:29.856291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9a478db66d5'
down_revision = '0da60609ddb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_playlist', sa.Column('video_id', sa.Integer(), nullable=False))
    op.drop_constraint('video_playlist_ibfk_2', 'video_playlist', type_='foreignkey')
    op.create_foreign_key(None, 'video_playlist', 'video', ['video_id'], ['id'], ondelete='CASCADE')
    op.drop_column('video_playlist', 'video_is')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_playlist', sa.Column('video_is', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'video_playlist', type_='foreignkey')
    op.create_foreign_key('video_playlist_ibfk_2', 'video_playlist', 'video', ['video_is'], ['id'], ondelete='CASCADE')
    op.drop_column('video_playlist', 'video_id')
    # ### end Alembic commands ###
