"""empty message

Revision ID: c21d14788831
Revises: 5a4be8b1736e
Create Date: 2019-02-24 22:11:00.673565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21d14788831'
down_revision = '5a4be8b1736e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist', 'enabled')
    # ### end Alembic commands ###
